# ShinyValidator configuration

# Application title
app_title: ShinyValidator Template

# Welcome message
welcome_message: This is where you put the welcome message!

# Secondary message
secondary_message: You can also put a secondary message here with more instructions, perhaps referencing a link with helpful links.

# Secondary message link
secondary_link_url: https://github.com/manybabies/ShinyValidator
secondary_link_text: For example, link to this app's Github repo.

# Main instructions
instructions_before: This is where you can provide specific instructions on how to use
instructions_emphasis: your
instructions_after: validator.

# File upload instructions
upload_instructions_before: Click
upload_instructions_emphasis: Browse
upload_instructions_after: to select the dataset you would like to validate.

# Specification tab
specification_message: This is the human-readable version of the specification you have chosen.
