theme: "purple"
app_title: ManyAllergies Data Validator
logo:
  enabled: no
  file: "ManyBabies.png"
  width: "240px"
welcome_message: Welcome to Anya's ManyAllergies project!
secondary_message: Please use this validator to check your data before submitting to the central analysis team.
instruction_set_1_name: Selecting the appropropriate specification
instruction_set_1:
- "From the 'Study' dropdown, please select the appropriate allergen condition: 'peanut', 'gluten', or 'soy'."
- "From the 'Study Format' dropdown, please select the appropriate age range for which you are validating data."
- "Click 'Browse' to upload your dataset for validation. "
links:
- text: Link to project manual
  url: https://google.ca
- text: Link to data submission page
  url: https://github.com/manybabies/ShinyValidator
instruction_set_2_name: Data submission instructions
instruction_set_2:
- "Once your dataset is validated, press the 'Download Validated CSV File' button"
- "Enter your assigned laboratory ID"
- "Download the exported .csv file WITHOUT MODIFYING THE FILE NAME. This autogenerated file name serves as authentication and verification that your dataset has been validated."
- "Upload your validated dataset to the central repository via the data submission page linked here."
specification_message: This is the human-readable version of the specification you
  have chosen.
